require 'faraday'
require 'json'

require 'similarweb/version'
require 'similarweb/also_visited'
require 'similarweb/category'
require 'similarweb/category_rank'
require 'similarweb/destinations'
require 'similarweb/engagement'
require 'similarweb/estimated_visits'
require 'similarweb/keywords'
require 'similarweb/referrals'
require 'similarweb/similar_sites'
require 'similarweb/social_referrals'
require 'similarweb/tags'
require 'similarweb/traffic'
require 'similarweb/visit_duration'
require 'similarweb/bounce_rate'
require 'similarweb/pageviews_per_visit'
require 'similarweb/global_rank'
require 'similarweb/geo_distribution'
require 'similarweb/client'

module Similarweb
end
